enum RideBookingStatus {
  initial,
  rideCreating,
  paymentAuthoriging,
  searchingDriver,
  driverOnTheWay,
  driverArived,
  rideStarted,
  rideCompleted,
  rideCancelled,
  giveReview,
  tipProcessing,
  paymentFailed,
  rideFailed,
  rideEnded,
}
