enum RideBookingStatus {
  initial,
  rideCreating,
  searchingDriver,
  driverOnTheWay,
  rideStarted,
  rideInProgress,
  rideCompleted,
  rideCancelled,
  paymentProcessing,
  paymentCompleted,
  paymentFailed,
  rideFailed,
  rideEnded,
}
